In [1]:
!pip install --upgrade tensorflow==1.15

Requirement already up-to-date: tensorflow==1.15 in /usr/local/lib/python3.7/dist-packages (1.15.0)


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow.compat.v1 as tf
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [3]:
data = pd.read_csv('classification.csv')
data

class cap-shape cap-surface  ...  spore-print-color  population habitat
0        p         x           s  ...                  2           s       u
1        e         x           s  ...                  3           n       g
2        e         b           s  ...                  3           n       m
3        p         x           y  ...                  2           s       u
4        e         x           s  ...                  3           a       g
...    ...       ...         ...  ...                ...         ...     ...
8119     e         k           s  ...                  0           c       l
8120     e         x           s  ...                  0           v       l
8121     e         f           s  ...                  0           c       l
8122     p         k           y  ...                  7           v       l
8123     e         x           s  ...                  4           c       l

[8124 rows x 19 columns]

In [4]:
for i in range(len(data)):
  if data['cap-shape'][i] == 's':
    data['cap-shape'][i] = 6
  elif data['cap-shape'][i] == 'k':
    data['cap-shape'][i] = 5
  elif data['cap-shape'][i] == 'f':
    data['cap-shape'][i] = 4
  elif data['cap-shape'][i] == 'x':
    data['cap-shape'][i] = 3
  elif data['cap-shape'][i] == 'c':
    data['cap-shape'][i] = 2
  elif data['cap-shape'][i] == 'b':
    data['cap-shape'][i] = 1
  
  if data['odor'][i] == 's':
    data['odor'][i] = 9
  elif data['odor'][i] == 'p':
    data['odor'][i] = 8
  elif data['odor'][i] == 'n':
    data['odor'][i] = 7
  elif data['odor'][i] == 'm':
    data['odor'][i] = 6
  elif data['odor'][i] == 'f':
    data['odor'][i] = 5
  elif data['odor'][i] == 'y':
    data['odor'][i] = 4
  elif data['odor'][i] == 'c':
    data['odor'][i] = 3
  elif data['odor'][i] == 'l':
    data['odor'][i] = 2
  elif data['odor'][i] == 'a':
    data['odor'][i] = 1

  if data['habitat'][i] == 'd':
    data['habitat'][i] = 7
  elif data['habitat'][i] == 'w':
    data['habitat'][i] = 6
  elif data['habitat'][i] == 'u':
    data['habitat'][i] = 5
  elif data['habitat'][i] == 'p':
    data['habitat'][i] = 4
  elif data['habitat'][i] == 'm':
    data['habitat'][i] = 3
  elif data['habitat'][i] == 'l':
    data['habitat'][i] = 2
  elif data['habitat'][i] == 'g':
    data['habitat'][i] = 1


data

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:39: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarn

class cap-shape cap-surface  ...  spore-print-color  population habitat
0        p         3           s  ...                  2           s       5
1        e         3           s  ...                  3           n       1
2        e         1           s  ...                  3           n       3
3        p         3           y  ...                  2           s       5
4        e         3           s  ...                  3           a       1
...    ...       ...         ...  ...                ...         ...     ...
8119     e         5           s  ...                  0           c       2
8120     e         3           s  ...                  0           v       2
8121     e         4           s  ...                  0           c       2
8122     p         5           y  ...                  7           v       2
8123     e         3           s  ...                  4           c       2

[8124 rows x 19 columns]

In [5]:
x_data = data[['cap-shape','cap-color','odor','stalk-color-above-ring','stalk-color-below-ring','veil-color','ring-number','habitat']]
y_data = data[['class']]

In [6]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler,OneHotEncoder


scaler = MinMaxScaler()
x_data = scaler.fit_transform(x_data)

encoder = OneHotEncoder(sparse=False)
y_data = encoder.fit_transform(y_data)

print(x_data)

pca = PCA(n_components=4)
pca = pca.fit(x_data)
x_data = pca.transform(x_data)
print(x_data)

[[0.4        0.44444444 0.875      ... 0.66666667 0.5        0.66666667]
 [0.4        1.         0.         ... 0.66666667 0.5        0.        ]
 [0.         0.88888889 0.125      ... 0.66666667 0.5        0.33333333]
 ...
 [0.6        0.44444444 0.75       ... 0.33333333 0.5        0.16666667]
 [0.8        0.44444444 0.375      ... 0.66666667 0.5        0.16666667]
 [0.4        0.44444444 0.75       ... 0.33333333 0.5        0.16666667]]
[[-0.12206932 -0.21781053 -0.15432083 -0.19677282]
 [ 0.78480668  0.4745793  -0.2639261   0.17431713]
 [ 0.46774485  0.4816881  -0.3659415   0.13117795]
 ...
 [ 0.25709894 -0.16874034  0.32529131 -0.02422538]
 [ 0.37314174 -0.14011849 -0.08675233  0.21334806]
 [ 0.2761574  -0.13207006  0.30324638 -0.01706583]]


In [7]:
#SPLIT DATA
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, train_size=0.7)

In [8]:
epochs = 2500
learning_rate = 0.01
n_features = x_train[0].shape[0]
n_classes = y_train[0].shape[0]

In [9]:
#neural network
input_tensor = tf.placeholder(tf.float32, name = 'input')
label_tensor = tf.placeholder(tf.float32, name = 'label')

In [10]:
neurons = [n_features, 3, n_classes]
n_layers = len(neurons)

In [11]:
parameters = {
    'W1' : tf.Variable(
        tf.random.normal([
            n_features, neurons[0]
        ]),
        tf.float32
    ),
    'B1' : tf.Variable(
        tf.random.normal([1,  neurons[0]]),
        tf.float32
    ),
    'W2' : tf.Variable(
        tf.random.normal([
            neurons[0], neurons[1]
        ]),
        tf.float32
    ),
    'B2' : tf.Variable(
        tf.random.normal([1,  neurons[1]]),
        tf.float32
    ),
    'W3' : tf.Variable(
        tf.random.normal([
            neurons[1], neurons[2]
        ]),
        tf.float32
    ),
    'B3' : tf.Variable(
        tf.random.normal([1,  neurons[2]]),
        tf.float32
    )
}

In [12]:
#FORWARD PASS
def forward_pass(input_tensor,params,n_layer=3):
  a = input_tensor
  for i in range(n_layer):
    W = params[f'W{i+1}']
    B = params[f'B{i+1}']

    z = tf.matmul(a,W) + B 
    if i == n_layer-1:
      a = tf.nn.sigmoid(z)
    else:
      a = tf.nn.sigmoid(z)

  return a 

In [13]:
def evaluate_accuracy(y, yhat):
  yield (0.5 * (yhat - y)**2).sum(axis=1).mean()
  yield accuracy_score(np.argmax(y, axis = 1), np.argmax(yhat, axis = 1))

In [14]:
with tf.Session() as sess: #jawban
  logits_tensor = forward_pass(input_tensor, parameters)
  loss_tensor = tf.losses.mean_squared_error(label_tensor, logits_tensor)
  true_preds_tensor = tf.equal(tf.argmax(logits_tensor, axis=1), tf.argmax(label_tensor, axis=1))
  acc_tensor = tf.reduce_mean(tf.cast(true_preds_tensor, tf.float32))

  optimiser = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss_tensor)
  sess.run(tf.global_variables_initializer())
  saver = tf.train.Saver()
  test_dict = {
      input_tensor: x_test,
      label_tensor: y_test
  }
  best_loss = float('inf')

  for i in range(epochs):
    sess.run(
        optimiser,
        feed_dict = {
            input_tensor: x_train,
            label_tensor: y_train
        }
    )

    if i%25 == 0:
      loss,acc = evaluate_accuracy(y_test,sess.run(
          logits_tensor,
          feed_dict = {
              input_tensor: x_test,
              label_tensor: y_test
          }
      ))
      print(f'Epochs: ',i, ' ||Loss: ',loss, ' ||Accuracy: ', {acc*100},'%')

    if i %125 == 0:
      # loss = sess.run(optimizer, feed_dict=train_dict)
      val_loss = sess.run(loss_tensor, feed_dict = test_dict)
      print(f'Epoch {i+1} - val_loss {val_loss}')

      if val_loss < best_loss:
        best_loss = val_loss
        saver.save(sess, 'best_model.ckpt')


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


NameError: ignored