#Mush Farmoatic - Classification

---


2301931251 - Daffa Rizki Rizaly

2301869840 - William Yulio


In [ ]:
#Import Library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow.compat.v1 as tf
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler,OneHotEncoder

In [ ]:
#Import Dataset
data = pd.read_csv('classification.csv')
data

class cap-shape cap-surface  ...  spore-print-color  population habitat
0        p         x           s  ...                  2           s       u
1        e         x           s  ...                  3           n       g
2        e         b           s  ...                  3           n       m
3        p         x           y  ...                  2           s       u
4        e         x           s  ...                  3           a       g
...    ...       ...         ...  ...                ...         ...     ...
8119     e         k           s  ...                  0           c       l
8120     e         x           s  ...                  0           v       l
8121     e         f           s  ...                  0           c       l
8122     p         k           y  ...                  7           v       l
8123     e         x           s  ...                  4           c       l

[8124 rows x 19 columns]

In [ ]:
#Feature Selection

for i in range(len(data)):
  #Cap Shape
  if data['cap-shape'][i] == 's':
    data['cap-shape'][i] = 6
  elif data['cap-shape'][i] == 'k':
    data['cap-shape'][i] = 5
  elif data['cap-shape'][i] == 'f':
    data['cap-shape'][i] = 4
  elif data['cap-shape'][i] == 'x':
    data['cap-shape'][i] = 3
  elif data['cap-shape'][i] == 'c':
    data['cap-shape'][i] = 2
  elif data['cap-shape'][i] == 'b':
    data['cap-shape'][i] = 1
  
  #Odor
  if data['odor'][i] == 's':
    data['odor'][i] = 9
  elif data['odor'][i] == 'p':
    data['odor'][i] = 8
  elif data['odor'][i] == 'n':
    data['odor'][i] = 7
  elif data['odor'][i] == 'm':
    data['odor'][i] = 6
  elif data['odor'][i] == 'f':
    data['odor'][i] = 5
  elif data['odor'][i] == 'y':
    data['odor'][i] = 4
  elif data['odor'][i] == 'c':
    data['odor'][i] = 3
  elif data['odor'][i] == 'l':
    data['odor'][i] = 2
  elif data['odor'][i] == 'a':
    data['odor'][i] = 1

  #Habitat
  if data['habitat'][i] == 'd':
    data['habitat'][i] = 7
  elif data['habitat'][i] == 'w':
    data['habitat'][i] = 6
  elif data['habitat'][i] == 'u':
    data['habitat'][i] = 5
  elif data['habitat'][i] == 'p':
    data['habitat'][i] = 4
  elif data['habitat'][i] == 'm':
    data['habitat'][i] = 3
  elif data['habitat'][i] == 'l':
    data['habitat'][i] = 2
  elif data['habitat'][i] == 'g':
    data['habitat'][i] = 1


data

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:36: SettingWithCopyWarning:

class cap-shape cap-surface  ...  spore-print-color  population habitat
0        p         3           s  ...                  2           s       5
1        e         3           s  ...                  3           n       1
2        e         1           s  ...                  3           n       3
3        p         3           y  ...                  2           s       5
4        e         3           s  ...                  3           a       1
...    ...       ...         ...  ...                ...         ...     ...
8119     e         5           s  ...                  0           c       2
8120     e         3           s  ...                  0           v       2
8121     e         4           s  ...                  0           c       2
8122     p         5           y  ...                  7           v       2
8123     e         3           s  ...                  4           c       2

[8124 rows x 19 columns]

In [ ]:
x_data = data[['cap-shape','cap-color','odor','stalk-color-above-ring','stalk-color-below-ring','veil-color','ring-number','habitat']]
y_data = data[['class']]

In [ ]:
scaler = MinMaxScaler()
x_data = scaler.fit_transform(x_data)

encoder = OneHotEncoder(sparse=False)
y_data = encoder.fit_transform(y_data)

print(x_data)

pca = PCA(n_components=4)
pca = pca.fit(x_data)
x_data = pca.transform(x_data)
print(x_data)

[[0.4        0.44444444 0.875      ... 0.66666667 0.5        0.66666667]
 [0.4        1.         0.         ... 0.66666667 0.5        0.        ]
 [0.         0.88888889 0.125      ... 0.66666667 0.5        0.33333333]
 ...
 [0.6        0.44444444 0.75       ... 0.33333333 0.5        0.16666667]
 [0.8        0.44444444 0.375      ... 0.66666667 0.5        0.16666667]
 [0.4        0.44444444 0.75       ... 0.33333333 0.5        0.16666667]]
[[-0.12206932 -0.21781053 -0.15432083 -0.19677282]
 [ 0.78480668  0.4745793  -0.2639261   0.17431713]
 [ 0.46774485  0.4816881  -0.3659415   0.13117795]
 ...
 [ 0.25709894 -0.16874034  0.32529131 -0.02422538]
 [ 0.37314174 -0.14011849 -0.08675233  0.21334806]
 [ 0.2761574  -0.13207006  0.30324638 -0.01706583]]


In [ ]:
layer = {
    'input' : 4,
    'hidden' : 3,
    'output' : 2
}

weight = {
    'to_hidden' : tf.Variable(tf.random.normal([layer['input'],layer['hidden']])),
    'to_output' : tf.Variable(tf.random.normal([layer['hidden'],layer['output']]))
}

bias = {
    'to_hidden' : tf.Variable(tf.random.normal([layer['hidden']])),
    'to_output' : tf.Variable(tf.random.normal([layer['output']]))
}


In [ ]:
#Spliting data
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data,train_size=0.7)

In [ ]:
#Spliting data for validation
x_validation, _, y_validation, _ = train_test_split(x_train, y_train, train_size=0.2)

In [ ]:
x = tf.placeholder(tf.float32, [None, layer['input']])
target = tf.placeholder(tf.float32, [None,layer['output']])

In [ ]:
def predict():
    wx_b1= tf.matmul(x, weight['to_hidden']) + bias['to_hidden']
    y1= tf.nn.sigmoid(wx_b1)

    wx_b2= tf.matmul(y1, weight['to_output']) + bias['to_output']
    y2= tf.nn.sigmoid(wx_b2)
    return y2

In [ ]:
y= predict()
epoch = 2500
alpha = 0.02
error = tf.reduce_mean(0.5 * (target - y) **2)
optimizer = tf.train.GradientDescentOptimizer(alpha)
train = optimizer.minimize(error)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [ ]:
with tf.Session() as sess:
  saver = tf.train.Saver()
  sess.run(tf.global_variables_initializer())
  best_error = float('inf')
  for i in range(epoch):
    sess.run(
        train,
        feed_dict = {
            x: x_train,
            target: y_train
        }
    )

    if i % 25 == 0:
      current_error = sess.run(
          error,
          feed_dict = {
              x: x_train,
              target: y_train
          }
      )
      print(f'EPOCH : {i} | ERROR : {current_error} |')
    if i % 125 == 0:
      validation_error = sess.run(
          error,
          feed_dict = {
              x: x_validation,
              target: y_validation
          }
      )
      if validation_error < best_error:
        saver.save(sess, './checkpoint.ckpt')
      print(f'EPOCH : {i} | VALIDATION_ERROR : {validation_error} |')

  true_prediction = tf.equal(tf.argmax(y, axis = 1), tf.argmax(target, axis = 1))
  accuracy = tf.reduce_mean(tf.cast(true_prediction, tf.float32))
  saver.restore(sess, './checkpoint.ckpt')
  accuracy = sess.run(
      accuracy,
      feed_dict = {
          x: x_test,
          target: y_test
      }
  )  
  print(f'ACCURACY: {accuracy:}')

EPOCH : 0 | ERROR : 0.15761640667915344 |
EPOCH : 0 | VALIDATION_ERROR : 0.15563686192035675 |
EPOCH : 25 | ERROR : 0.15673409402370453 |
EPOCH : 50 | ERROR : 0.15586182475090027 |
EPOCH : 75 | ERROR : 0.1550002545118332 |
EPOCH : 100 | ERROR : 0.15414953231811523 |
EPOCH : 125 | ERROR : 0.15331028401851654 |
EPOCH : 125 | VALIDATION_ERROR : 0.15149499475955963 |
EPOCH : 150 | ERROR : 0.1524830162525177 |
EPOCH : 175 | ERROR : 0.1516677439212799 |
EPOCH : 200 | ERROR : 0.15086516737937927 |
EPOCH : 225 | ERROR : 0.150075301527977 |
EPOCH : 250 | ERROR : 0.1492988020181656 |
EPOCH : 250 | VALIDATION_ERROR : 0.1476442515850067 |
EPOCH : 275 | ERROR : 0.14853565394878387 |
EPOCH : 300 | ERROR : 0.14778628945350647 |
EPOCH : 325 | ERROR : 0.14705094695091248 |
EPOCH : 350 | ERROR : 0.14632977545261383 |
EPOCH : 375 | ERROR : 0.14562299847602844 |
EPOCH : 375 | VALIDATION_ERROR : 0.14412419497966766 |
EPOCH : 400 | ERROR : 0.1449308842420578 |
EPOCH : 425 | ERROR : 0.14425350725650787 |
EPO